const amqp = require('amqplib');

const queueNames = ['Broker1', 'Broker2', 'Broker3', 'Broker4'];
const jsonData = [
    {
        "nSsi_id": 1,
        "nSus_ID": 1,
        "cSus_Empresa": "ROOT",
        "dSsi_FechaInicio": "2022-11-07",
        "dSsi_FechaInicio2": "07/11/2022",
        "nPla_ID": 74,
        "cPla_Nombre": "Demo",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 206,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2022-11-07T20:25:08.000Z",
        "dSsi_FechaVencimiento": "2025-11-07",
        "dSsi_FechaVencimiento2": "07/11/2025",
        "dSsi_FechaProxPago": "2025-11-07T05:00:00.000Z",
        "cSsi_BD": "GPSPaas",
        "cSsi_Cuenta": "newpaas",
        "bSsi_CuentaConfirmada": 1,
        "cSsi_Fac_Compania": "ROOT",
        "cSsi_Fac_Ruc": "0000000000",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "ROOT",
        "cSsi_Fac_Apellido": null,
        "cSsi_Fac_Correo": "johanrojasn21@gmail.com",
        "cSsi_Fac_Telefono": "998440020",
        "cSsi_Fac_DireccionL1": null,
        "cSsi_Fac_DireccionL2": null,
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": null
    },
    {
        "nSsi_id": 2,
        "nSus_ID": 1,
        "cSus_Empresa": "ROOT",
        "dSsi_FechaInicio": "2022-11-30",
        "dSsi_FechaInicio2": "30/11/2022",
        "nPla_ID": 74,
        "cPla_Nombre": "Demo",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 206,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2022-11-08T00:39:18.000Z",
        "dSsi_FechaVencimiento": "2099-11-30",
        "dSsi_FechaVencimiento2": "30/11/2099",
        "dSsi_FechaProxPago": "2099-11-30T05:00:00.000Z",
        "cSsi_BD": "GPSPaas",
        "cSsi_Cuenta": "solicitatudemo",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "ROOT",
        "cSsi_Fac_Ruc": "0000000000",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "ROOT",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "johanrojasn21@gmail.com",
        "cSsi_Fac_Telefono": "998440020",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 3,
        "nSus_ID": 1,
        "cSus_Empresa": "ROOT",
        "dSsi_FechaInicio": "2022-11-29",
        "dSsi_FechaInicio2": "29/11/2022",
        "nPla_ID": 74,
        "cPla_Nombre": "Demo",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 206,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2022-11-17T01:12:27.000Z",
        "dSsi_FechaVencimiento": "2099-11-30",
        "dSsi_FechaVencimiento2": "30/11/2099",
        "dSsi_FechaProxPago": "2099-11-30T05:00:00.000Z",
        "cSsi_BD": "GPSPaas",
        "cSsi_Cuenta": "http://localhost:82",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "ROOT",
        "cSsi_Fac_Ruc": "0000000000",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "ROOT",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 61,
        "nSus_ID": 25,
        "cSus_Empresa": "Empresa A",
        "dSsi_FechaInicio": "2024-08-01",
        "dSsi_FechaInicio2": "01/08/2024",
        "nPla_ID": 92,
        "cPla_Nombre": "Plan para gobierno",
        "nPro_ID": 61,
        "cPro_Nombre": "Gobierno",
        "nTaf_ID": 258,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2022-11-17T01:12:06.000Z",
        "dSsi_FechaVencimiento": "2024-08-31",
        "dSsi_FechaVencimiento2": "31/08/2024",
        "dSsi_FechaProxPago": "2024-08-31T05:00:00.000Z",
        "cSsi_BD": "db_0000",
        "cSsi_Cuenta": "http://localhost:81",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Estudio Infante Angeles ||",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto A",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 63,
        "nSus_ID": 26,
        "cSus_Empresa": "Empresa B",
        "dSsi_FechaInicio": "2023-09-02",
        "dSsi_FechaInicio2": "02/09/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED02",
        "cSsi_Estado2": "Suspendido",
        "dSsi_FechaCreacion": "2022-11-17T01:13:13.000Z",
        "dSsi_FechaVencimiento": "2023-09-30",
        "dSsi_FechaVencimiento2": "30/09/2023",
        "dSsi_FechaProxPago": "2023-09-30T05:00:00.000Z",
        "cSsi_BD": "db_0000",
        "cSsi_Cuenta": "B1",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa B",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto B",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 64,
        "nSus_ID": 26,
        "cSus_Empresa": "Empresa B",
        "dSsi_FechaInicio": "2023-09-02",
        "dSsi_FechaInicio2": "02/09/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED02",
        "cSsi_Estado2": "Suspendido",
        "dSsi_FechaCreacion": "2022-11-17T01:13:13.000Z",
        "dSsi_FechaVencimiento": "2023-09-30",
        "dSsi_FechaVencimiento2": "30/09/2023",
        "dSsi_FechaProxPago": "2023-09-30T05:00:00.000Z",
        "cSsi_BD": "db_0000",
        "cSsi_Cuenta": "B2",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa B",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto B",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 65,
        "nSus_ID": 26,
        "cSus_Empresa": "Empresa B",
        "dSsi_FechaInicio": "2023-09-02",
        "dSsi_FechaInicio2": "02/09/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED02",
        "cSsi_Estado2": "Suspendido",
        "dSsi_FechaCreacion": "2022-11-17T01:13:13.000Z",
        "dSsi_FechaVencimiento": "2023-09-30",
        "dSsi_FechaVencimiento2": "30/09/2023",
        "dSsi_FechaProxPago": "2023-09-30T05:00:00.000Z",
        "cSsi_BD": "db_0000",
        "cSsi_Cuenta": "B3",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa B",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto B",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 66,
        "nSus_ID": 26,
        "cSus_Empresa": "Empresa B",
        "dSsi_FechaInicio": "2023-09-02",
        "dSsi_FechaInicio2": "02/09/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED02",
        "cSsi_Estado2": "Suspendido",
        "dSsi_FechaCreacion": "2022-11-17T01:13:13.000Z",
        "dSsi_FechaVencimiento": "2023-09-30",
        "dSsi_FechaVencimiento2": "30/09/2023",
        "dSsi_FechaProxPago": "2023-09-30T05:00:00.000Z",
        "cSsi_BD": "db_0000",
        "cSsi_Cuenta": "B4",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa B",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto B",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 67,
        "nSus_ID": 26,
        "cSus_Empresa": "Empresa B",
        "dSsi_FechaInicio": "2023-09-02",
        "dSsi_FechaInicio2": "02/09/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED02",
        "cSsi_Estado2": "Suspendido",
        "dSsi_FechaCreacion": "2022-11-17T01:13:13.000Z",
        "dSsi_FechaVencimiento": "2023-09-30",
        "dSsi_FechaVencimiento2": "30/09/2023",
        "dSsi_FechaProxPago": "2023-09-30T05:00:00.000Z",
        "cSsi_BD": "db_0000",
        "cSsi_Cuenta": "B5",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa B",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto B",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 68,
        "nSus_ID": 26,
        "cSus_Empresa": "Empresa B",
        "dSsi_FechaInicio": "2023-09-02",
        "dSsi_FechaInicio2": "02/09/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED02",
        "cSsi_Estado2": "Suspendido",
        "dSsi_FechaCreacion": "2022-10-01T05:00:00.000Z",
        "dSsi_FechaVencimiento": "2023-09-30",
        "dSsi_FechaVencimiento2": "30/09/2023",
        "dSsi_FechaProxPago": "2022-11-01T05:00:00.000Z",
        "cSsi_BD": "db_0000",
        "cSsi_Cuenta": "B6",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa B",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto B",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 69,
        "nSus_ID": 25,
        "cSus_Empresa": "Empresa A",
        "dSsi_FechaInicio": "2023-07-24",
        "dSsi_FechaInicio2": "24/07/2023",
        "nPla_ID": 110,
        "cPla_Nombre": "catillo plan",
        "nPro_ID": 61,
        "cPro_Nombre": "Gobierno",
        "nTaf_ID": 296,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-07-25T04:15:28.000Z",
        "dSsi_FechaVencimiento": "2024-07-20",
        "dSsi_FechaVencimiento2": "20/07/2024",
        "dSsi_FechaProxPago": "2024-07-20T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "demo_prueba_susi",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa A",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto A",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "av jose olaya 777",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": "Lima"
    },
    {
        "nSsi_id": 70,
        "nSus_ID": 35,
        "cSus_Empresa": "Wong SA",
        "dSsi_FechaInicio": "2023-08-01",
        "dSsi_FechaInicio2": "01/08/2023",
        "nPla_ID": 85,
        "cPla_Nombre": "Estudiante 300",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 233,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-08-01T21:52:50.000Z",
        "dSsi_FechaVencimiento": "2023-08-31",
        "dSsi_FechaVencimiento2": "31/08/2023",
        "dSsi_FechaProxPago": "2023-08-31T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "cb demo_active_sub",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Wong SA",
        "cSsi_Fac_Ruc": "1147099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Calla Wong",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 71,
        "nSus_ID": 35,
        "cSus_Empresa": "Wong SA",
        "dSsi_FechaInicio": "2023-08-01",
        "dSsi_FechaInicio2": "01/08/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-08-01T22:08:38.000Z",
        "dSsi_FechaVencimiento": "2023-08-31",
        "dSsi_FechaVencimiento2": "31/08/2023",
        "dSsi_FechaProxPago": "2023-08-31T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "demo_AA",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Wong SA",
        "cSsi_Fac_Ruc": "1147099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Calla Wong",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 72,
        "nSus_ID": 35,
        "cSus_Empresa": "Wong SA",
        "dSsi_FechaInicio": "2023-07-03",
        "dSsi_FechaInicio2": "03/07/2023",
        "nPla_ID": 85,
        "cPla_Nombre": "Estudiante 300",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 234,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-06-03T21:16:10.000Z",
        "dSsi_FechaVencimiento": "2024-01-30",
        "dSsi_FechaVencimiento2": "30/01/2024",
        "dSsi_FechaProxPago": "2024-01-30T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "San_Martin_edu",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Wong SA",
        "cSsi_Fac_Ruc": "1147099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Calla Wong",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 73,
        "nSus_ID": 32,
        "cSus_Empresa": "Estudio Infante Angeles",
        "dSsi_FechaInicio": "2023-08-01",
        "dSsi_FechaInicio2": "01/08/2023",
        "nPla_ID": 8,
        "cPla_Nombre": "Corporativo 1000",
        "nPro_ID": 2,
        "cPro_Nombre": "Corporativo ",
        "nTaf_ID": 23,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-08-05T09:08:31.000Z",
        "dSsi_FechaVencimiento": "2023-08-31",
        "dSsi_FechaVencimiento2": "31/08/2023",
        "dSsi_FechaProxPago": "2023-08-31T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "Dominium",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Estudio Infante Angeles",
        "cSsi_Fac_Ruc": null,
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Pedro Gomes",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "johanrojasn21@gmail.com",
        "cSsi_Fac_Telefono": "956973863",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 74,
        "nSus_ID": 25,
        "cSus_Empresa": "Empresa A",
        "dSsi_FechaInicio": "2024-08-01",
        "dSsi_FechaInicio2": "01/08/2024",
        "nPla_ID": 9,
        "cPla_Nombre": "Estudio 100",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 85,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-08-05T09:10:08.000Z",
        "dSsi_FechaVencimiento": "2024-08-31",
        "dSsi_FechaVencimiento2": "31/08/2024",
        "dSsi_FechaProxPago": "2024-08-31T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "Gumoni",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa A",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto A",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 75,
        "nSus_ID": 26,
        "cSus_Empresa": "Empresa B",
        "dSsi_FechaInicio": "2023-07-04",
        "dSsi_FechaInicio2": "04/07/2023",
        "nPla_ID": 74,
        "cPla_Nombre": "Demo",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 206,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-08-07T09:11:33.000Z",
        "dSsi_FechaVencimiento": "2023-08-08",
        "dSsi_FechaVencimiento2": "08/08/2023",
        "dSsi_FechaProxPago": "2023-08-08T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "Prolog",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Empresa B",
        "cSsi_Fac_Ruc": "1047099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Contacto B",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 76,
        "nSus_ID": 35,
        "cSus_Empresa": "Wong SA",
        "dSsi_FechaInicio": "2023-08-01",
        "dSsi_FechaInicio2": "01/08/2023",
        "nPla_ID": 31,
        "cPla_Nombre": "Independiente 500",
        "nPro_ID": 4,
        "cPro_Nombre": "Independiente",
        "nTaf_ID": 78,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-08-11T18:14:47.000Z",
        "dSsi_FechaVencimiento": "2024-02-29",
        "dSsi_FechaVencimiento2": "29/02/2024",
        "dSsi_FechaProxPago": "2024-02-29T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "maru",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Wong SA",
        "cSsi_Fac_Ruc": "1147099414",
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Calla Wong",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "hernanriosvalencia92@gmail.com",
        "cSsi_Fac_Telefono": "923296190",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    },
    {
        "nSsi_id": 77,
        "nSus_ID": 34,
        "cSus_Empresa": "Estudio Infante Angeles",
        "dSsi_FechaInicio": "2023-08-01",
        "dSsi_FechaInicio2": "01/08/2023",
        "nPla_ID": 74,
        "cPla_Nombre": "Demo",
        "nPro_ID": 3,
        "cPro_Nombre": "Estudio",
        "nTaf_ID": 206,
        "cSsi_Estado": "ED01",
        "cSsi_Estado2": "Vigente",
        "dSsi_FechaCreacion": "2023-08-15T02:30:08.000Z",
        "dSsi_FechaVencimiento": "2023-08-31",
        "dSsi_FechaVencimiento2": "31/08/2023",
        "dSsi_FechaProxPago": "2023-08-31T05:00:00.000Z",
        "cSsi_BD": "db_0003",
        "cSsi_Cuenta": "dominos",
        "bSsi_CuentaConfirmada": 0,
        "cSsi_Fac_Compania": "Estudio Infante Angeles",
        "cSsi_Fac_Ruc": null,
        "cSsi_Fac_tab_formaPago": "BD01",
        "cSsi_Fac_Nombres": "Pedro Gomes",
        "cSsi_Fac_Apellido": "",
        "cSsi_Fac_Correo": "johanrojasn21@gmail.com",
        "cSsi_Fac_Telefono": "51956973863",
        "cSsi_Fac_DireccionL1": "",
        "cSsi_Fac_DireccionL2": "",
        "cSsi_Fac_Pais": "PD01",
        "cSsi_Fac_Ciudad": ""
    }
];


const chunkSize = Math.ceil(jsonData.length / 4);
function chunkArray(array, size) {
    const result = [];
    for (let i = 0; i < array.length; i += size) {
        result.push(array.slice(i, i + size));
    }
    return result;
}

async function runSendBrokers() {
    try {
        const connection = await amqp.connect('amqp://localhost')
        const channel = await connection.createChannel();
        for (let i = 0; i < queueNames.length; i++) {
            const queue = queueNames[i];
            await channel.assertQueue(queue, {
                durable: true,
                autoDelete: true,
            })
            channel.prefetch(1);
            const chunkedArrays = chunkArray(jsonData, chunkSize);
            for (let e = 0; e < chunkedArrays[i].length; e++) {
                channel.sendToQueue(queue, Buffer.from(JSON.stringify(chunkedArrays[i][e])))
                console.log(queue, i, `Send Menssage: ${new Date().toISOString()}`)
            }
        }


    } catch (error) {
        process.exit()
    } finally {
        process.exit()
    }
}


runSendBrokers()
